### ISSUE TITLE
cross-compile i386 kernel

### ISSUE THREAD

**Issue by sergiusens** [snapcore/snapcraft#1437]
[bug](https://bugs.launchpad.net/snapcraft/+bug/1563363) [forum](https://forum.snapcraft.io/t/cross-compiling-an-i386-kernel-snap/2182)

**Comment by kalikiana** [comment]
This requires some more investigation since it's a bit special since from x86-64 it's not really cross-compiling in the general sense - see notes on the bug. In hindsight I regret not having made this a forum topic right away since the bug is not receiving any responses...

**Comment by sergiusens** [comment]
Research at the sprint/rally with @piso77

**Comment by sergiusens** [comment]
Fixed with #1613
