### ISSUE TITLE
cross-compile python

### ISSUE THREAD

**Issue by sergiusens** [snapcore/snapcraft#1438]
[design](https://forum.snapcraft.io/t/cross-compile-support-for-python-plugin/1286/3)

**Comment by kalikiana** [comment]
This requires more investigation on the best approach and is partly blocked on other issues.
# Cross-compilation within a container depends on #1476 (and less so on #1502)
# Getting a target toolchain from a part built from source (or build snap)
So I'm going to focus on the mutli-arch work before picking this up again.
