### ISSUE TITLE
catkin pip support

### ISSUE THREAD

**Issue by sergiusens** [snapcore/snapcraft#1444]
[design](https://forum.snapcraft.io/t/proposal-catkin-pip-support/2083)

**Comment by sergiusens** [comment]
#1479 and LP: #1683036 make progress on by adding the ability for rosdep to parse multiple dependency types. It also updates the catkin plugin to support the new API, but it still only supports debs right now (it'll raise an exception if the dependency type is anything else). This is paving the way for support of pip dependencies coming from rosdep. Actually supporting this will require some experimentation, and of course, a design proposal.

**Comment by kyrofa** [comment]
More progress in #1540, where some helpers are being moved out of the Python plugin into a place where Catkin can also use them.

**Comment by kyrofa** [comment]
After the pip extraction lands, there's only one more PR as part of this. I expect this feature to be done this week.
