### ISSUE TITLE
on and from selectors for multi-arch build packages

### ISSUE THREAD

**Issue by sergiusens** [snapcore/snapcraft#1477]
#1346 [design](https://forum.snapcraft.io/t/multi-arch-build-packages/1678)

**Comment by kalikiana** [comment]
Superseded by #1502 and #1492

**Comment by sergiusens** [comment]
Please don't close issues.

**Comment by kalikiana** [comment]
To clarify here, I was gonna close this and create one for the new **on** and **from** selector designs, since it's very different. But I'm re-purposing this issue instead. I'm focussing on #1502 atm, and will add this after that's done.
