### ISSUE TITLE
Unable to specify make arguments

### ISSUE THREAD

**Issue by akashrajkn** [snapcore/snapcraft#1543]
I am trying to build a qt5 snap (app uses webkit). And I need to specify make arguments to "qmake"

I tried
```
parts:
    application:
        plugin: qmake --make-args="CONFIG+=foo"
```
Using the above, I get the following error
> Issue while loading part: unknown plugin: qmake --make-args="CONFIG+=foo"

**Comment by kalikiana** [comment]
You're mixing up the plugin name with plugin-specific options. It should look like so:

    parts:
        application:
            plugin: qmake
            options:
                - --make-args="CONFIG+=foo"

Have a look at `snapcraft help qmake` for more details.

**Comment by kalikiana** [comment]
Did you get it to work in the meantime?

**Comment by akashrajkn** [comment]
@kalikiana thank you, I am able to specify arguments in the correct manner. (I still haven't been able to build it successfully though - could be a qt related problem, but it solves this issue)
