### ISSUE TITLE
Homebrew still on snapcraft 2.33

### ISSUE THREAD

**Issue by jedvardsson** [snapcore/snapcraft#1604]
Homebrew is till on snap craft 2.33: [homebrew-core/Formula/snapcraft.rb](https://github.com/Homebrew/homebrew-core/blob/master/Formula/snapcraft.rb)

I am not sure who is the maintainer of the Homebrew formula for snapcraft but since it is mentioned on the 2.34 release notes I posted an issue here.

**Comment by kalikiana** [comment]
Would you please file your bug on Launchpad? We only use GitHub issues in order to use Projects. Please see #100 for specifics.
