### ISSUE TITLE
Change file migrations such that files move from stage to prime rather than coming from the part each time

### ISSUE THREAD

**Issue by sergiusens** [snapcore/snapcraft#1670]
Estimate: 1 week

We currently have three scriptlets that cover the build step only: prepare, build, and install. We want scriptlets around all lifecycle steps: pull, build, stage, and prime. Note that introducing an install step is not part of this roadmap.

There are some complications here that I want to point out. The stage and prime steps are completely handled by the core right now. As soon as we change that and provide the ability to override them, we must account for the possibility that files in stage will be changed from what they were in install, etc. Which means the stage dir must flow to the prime dir, which it does not do today (the file list is retrieved from stage, but the files themselves come from the parts’ install dirs).

Note that the stanzas for pull and build can be completed without such a redesign.

**Comment by kyrofa** [comment]
Wha... I thought I was insane, but then I found LP: [#1537850](https://bugs.launchpad.net/snapcraft/+bug/1537850). Regardless of what things used to be, this no longer seems to be the case, which means we don't seem to need this redesign, particularly now that the `stage` filter is inherited into the `prime` filter. We might want to consider no longer using hard links, however.

**Comment by sergiusens** [comment]
This no longer seems to be needed, so closing, please create a separate bug for the need of not using hard links
