### ISSUE TITLE
Documentation overhaul for scriptlets and setters

### ISSUE THREAD

**Issue by sergiusens** [snapcore/snapcraft#1680]
Estimate: 2 days

We currently have three scriptlets that cover the build step only: prepare, build, and install. We want scriptlets around all lifecycle steps: pull, build, stage, and prime. Note that introducing an install step is not part of this roadmap.

There are some complications here that I want to point out. The stage and prime steps are completely handled by the core right now. As soon as we change that and provide the ability to override them, we must account for the possibility that files in stage will be changed from what they were in install, etc. Which means the stage dir must flow to the prime dir, which it does not do today (the file list is retrieved from stage, but the files themselves come from the parts’ install dirs).

Note that the stanzas for pull and build can be completed without such a redesign.

**Comment by kyrofa** [comment]
Here it is: https://github.com/canonical-docs/snappy-docs/pull/383

**Comment by kyrofa** [comment]
Also in the forum: https://forum.snapcraft.io/t/scriptlets/4892
