### ISSUE TITLE
Design/document support for architecture selection during builds

### ISSUE THREAD

**Issue by sergiusens** [snapcore/snapcraft#1681]
Estimate: 1 day

Snapd’s snap.yaml supports an architectures keyword that defines the architectures on which that particular snap runs. Snapcraft currently supports the same keyword, and it acts as a pass-through, copying it into the snap.yaml. Now that build.snapcraft.io is a thing, we’d like to expand the architectures keyword to also serve the purpose of telling build.snapcraft.io which architectures to use for building, and on which architectures the resulting snap runs.

**Comment by kyrofa** [comment]
Note that the description on this issue covers way more than just making the keyword grammar-powered.

**Comment by sergiusens** [comment]
Yeah, the description is the whole thing, and it is copy pasted along the entire lane.

**Comment by sergiusens** [comment]
https://www.amazon.com/photos/share/7kcMwZif1Ap8HlPrWRwH7vaUz3mubXEwbzBVlmCxWyD

**Comment by kyrofa** [comment]
Proposal discussion is ongoing here: https://forum.snapcraft.io/t/proposal-architectures-keyword-for-snap-ci-systems/4675

**Comment by kyrofa** [comment]
Final docs given here: https://forum.snapcraft.io/t/architectures/4972 .
