### ISSUE TITLE
Implement support for architecture in snapcraft.yaml

### ISSUE THREAD

**Issue by sergiusens** [snapcore/snapcraft#1685]

**Comment by kyrofa** [comment]
Proposal has changed a bit, discussion is ongoing here: https://forum.snapcraft.io/t/proposal-architectures-keyword-for-snap-ci-systems/4675

**Comment by kyrofa** [comment]
Due to the redesign, this likely won't make it for this milestone, so we'll focus on docs instead.

**Comment by om26er** [comment]
This might be the wrong place to ask but when is build.snapcraft.io expected to respect this change ?

**Comment by kyrofa** [comment]
Hey @om26er, that's a question for @cjwatson now that this feature has actually landed. I was planning on letting him know this was done tomorrow, but this works too. I suspect they'll at least want to wait until this has been SRU'd.

**Comment by cjwatson** [comment]
It'll take some work in any case, and somebody should open a bug on Launchpad with a summary of what we need to do (we should dig up the minutes of the discussion in New York about this).  Also, I mentioned in New York that we were going to need a Python 2-compatible parser that we could use, preferably as something on PyPI that we could add to our dependencies.  Did that happen, or is there an updated plan?
