### ISSUE TITLE
Support strings in grammar

### ISSUE THREAD

**Issue by sergiusens** [snapcore/snapcraft#1686]
Estimate: 1 week

Snapcraft currently has a grammar that allows for behavior to change based on, for example, the host architecture. The use of this grammar is slowly making its way across the snapcraft.yaml. Currently the only items supported are lists (e.g. stage-packages and build-packages). Adding support for strings is required to support further expansion (e.g. making the source key grammar-powered).

**Comment by sergiusens** [comment]
This was not needed as the change was simple enough to support sources

**Comment by om26er** [comment]
> Currently the only items supported are lists (e.g. stage-packages and build-packages)

@sergiusens Does that mean, its already possible to have different stage-packages based on the architecture ? -- Can you please point to any examples for that ?

my usecase: I want to stage some 32bit packages on my 64bit snap. Currently those packages are also being shipped with 32bit snap, which doesn't need them.

**Comment by sergiusens** [comment]
On Dec 21 2017, at 6:04 pm, Omer Akram <notifications@github.com> wrote:
> >
> > Currently the only items supported are lists (e.g. stage-packages and build-packages)
> >
>
>
> @sergiusens (https://github.com/sergiusens) Does that mean, its already possible to have different stage-packages based on the architecture ? -- Can you please point to any examples for that ?
>
>
> my usecase: I want to stage some 32bit packages on my 64bit snap. Currently those packages are also being shipped with 32bit snap, which doesn't need them.
>
>

It is all documented here https://docs.snapcraft.io/build-snaps/syntax
