### ISSUE TITLE
Documentation for advanced grammar for sources

### ISSUE THREAD

**Issue by sergiusens** [snapcore/snapcraft#1688]
Estimate: 1 day

Snapcraft currently has a grammar that allows for behavior to change based on, for example, the host architecture. The use of this grammar is slowly making its way across the snapcraft.yaml. Currently the only items supported are lists (e.g. stage-packages and build-packages). Adding support for strings is required to support further expansion (e.g. making the source key grammar-powered).

**Comment by kyrofa** [comment]
David is working on restructuring the syntax page. Once that's done, we've agreed that this will go there.

**Comment by kyrofa** [comment]
Syntax update PR is here, undergoing review now: https://github.com/canonical-docs/snappy-docs/pull/306

**Comment by kyrofa** [comment]
[Here's my addition to it](https://github.com/kyrofa/snappy-docs/blob/snapcraft-syntax-grammar/build-snaps/syntax.md). I'll propose once the above PR is merged.

**Comment by kyrofa** [comment]
Alright, all merged and good to go.
