### ISSUE TITLE
Please upgrade brew version

### ISSUE THREAD

**Issue by fengerzh** [snapcore/snapcraft#1773]
Now the brew version of snapcraft on http://brewformulas.org/Snapcraft is still 2.33, please upgrade it to 2.35 to add Ruby support. Thanks!

**Comment by sergiusens** [comment]
As specified in the template when creating issues, this is not the correct place to log them.

That said, the formula will eventually be updated.

Cheers,
Sergio

**Comment by fengerzh** [comment]
But it's already 2018, and brew formula still not updated.
