### ISSUE TITLE
Proxy support?

### ISSUE THREAD

**Issue by array42** [snapcore/snapcraft#1777]
snap install does not work behind network proxy -> timeout

I tried snap on fedora 26 and the only thing i can manage it to do is 'snap download' with http_proxy environment set. But snap install <file>.snap warns that metadata and signatures are missing. The documentation mostly cares about ubuntu and not about other environments and since I did not find a bug over at https://bugs.launchpad.net/snapcraft regarding anything http_proxy related.. here we go.

**Comment by kyrofa** [comment]
As mentioned in the issue template, bugs are tracked over in [Launchpad](https://bugs.launchpad.net/snapcraft). However, I'll point out quickly that it doesn't look like you made it very far in the [documentation](https://docs.snapcraft.io/core/usage). Try `snap install` instead of `snap download`.

**Comment by array42** [comment]
snap install does not download at all. That is the issue I tried to bring up. snap download downloads it. I searched launchpad and I studied the documentation and I customized my environment files.

**Comment by kyrofa** [comment]
Alright, log a bug against [snapd](https://launchpad.net/snapd). In order to install something fetched with `snap download`, you need to `snap ack` the .assert file downloaded, and _then_ `snap install` the .snap file.
