### ISSUE TITLE
Feature Request: NGINX plugin

### ISSUE THREAD

**Issue by jamesbeedy** [snapcore/snapcraft#1834]
NGINX is fairly common component, I feel it would be best served as a formal plugin.

[Here](http://paste.ubuntu.com/26281664/) is an informal plugin for NGINX that I've been packing around for some time, and is now becoming a fragmented thing that I maintain all over the map.

I would be willing to put in the brunt of the work here, this being my second plugin attempt I think it would go far smoother then the first.

thoughts?

**Comment by kalikiana** [comment]
That looks awesome!

Please note that we track bugs and feature requests on [Launchpad](https://bugs.launchpad.net/snapcraft) - issues are only used for the Projects feature. I would actually suggest [a new topic on the forum](https://forum.snapcraft.io/c/snapcraft) to propose the new plugin, so anyone interested can give some early feedback and discuss.
