### ISSUE TITLE
Can't run snapd on Codenvy 5.22.0

### ISSUE THREAD

**Issue by 20avva** [snapcore/snapcraft#1837]
I am running snapd on Codenvy 5.22.0 in a Ubuntu 16.04.3 LTS workspace. Codenvy is based off of Eclipse Che.

When I try to run `sudo snap install my-snap-name_0.1_amd64.snap --devmode --dangerous` I get the error `error: cannot communicate with server: Post http://localhost/v2/snaps: dial unix /run/snapd.socket: connect: no such file or directory`

`snapcraft`-ing works normally, but I can't install them using `snap install`

**Comment by kalikiana** [comment]
Please note that we track bugs and feature requests on [Launchpad](https://bugs.launchpad.net/snapcraft) - issues are only used for the Projects feature. If you can instead file a bug on Launchpad that'd be much appreciated.
