### ISSUE TITLE
Cleanbuild doesn't work with SSH based Git repos

### ISSUE THREAD

**Issue by ted-gould** [snapcore/snapcraft#1876]
I put a source tag in a part that was SSH based Git repo (on Github). When I did a clean build I get this guy:

```
The authenticity of host 'github.com (192.30.253.113)' can't be established.
RSA key fingerprint is SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8.
Are you sure you want to continue connecting (yes/no)?
```

It shouldn't be verifying hosts when doing cleanbuilds.

**Comment by ted-gould** [comment]
Workaround is to switch to HTTPS based Git URLs.

**Comment by kalikiana** [comment]
Please note that we track bugs and feature requests on [Launchpad](https://bugs.launchpad.net/snapcraft) - issues are only used for the Projects feature. I'd appreciate if you can file a bug report.
