### ISSUE TITLE
rust plugin: i386 multiarch linker error 

### ISSUE THREAD

**Issue by General-Beck** [snapcore/snapcraft#1939]
[build log](https://gitlab.parity.io/parity/parity/-/jobs/79681)
Host: amd64
[build script](https://gitlab.parity.io/parity/parity/blob/snapcraft/scripts/gitlab-build.sh#L175)
[docker container for CI](https://hub.docker.com/r/parity/rust-i686/)

**Comment by kalikiana** [comment]
We only use GitHub issues for the Project feature. Would you please instead [file a bug report on Launchpad](https://bugs.launchpad.net/snapcraft)?

Or alternatively [open a topic to discuss it in the Snapcraft forum](https://forum.snapcraft.io/).
