### ISSUE TITLE
Distrubuted ROS system among multiple snaps

### ISSUE THREAD

**Issue by Lingaprahasam** [snapcore/snapcraft#1991]
**Please log issues on the project's [bug tracker](https://bugs.launchpad.net/snapcraft)**

Alternatively, If you are looking for support, try [posting on the forums](https://forum.snapcraft.io)

Hi,

I already posted the same problem in snapcraft forum.
https://forum.snapcraft.io/t/existing-snapcraft-yaml-not-building-a-snap/4333/6

Earlier I was using "run-system:" in my snapcraft.yaml file.

name: ros-app
version: '1.0'
grade: devel
confinement: devmode
summary: ROS App Snap
description: Contains talker ROS packages and a talker.launch file.

plugs:
  # Mount the content shared from ros-base into $SNAP/ros-base
  ros-base:
    content: ros-base-v1
    interface: content
    target: /ros-base

apps:
  launch-project:
    command: run-system
    plugs: [network, network-bind, ros-base]

parts:
  # The `source` here is the tarred staging area of the ros-base snap.
  ros-base:
    plugin: dump
    source: ros-base.tar.bz2

    # This is only used for building-- filter it out of the final snap.
    prime: [-*]

  # This is mostly unchanged from the standalone ROS example. Notable
  # additions are:
  #  - Using Kinetic now (other demo is Indigo)
  #  - Specifically not including roscore
  #  - Making sure we're building AFTER our underlay
  #  - Specifying the build- and run-time paths of the underlay
  ros-app:
    plugin: catkin
    rosdistro: kinetic
    include-roscore: false
    underlay:
      # Build-time location of the underlay
      # On Pi Platform
      build-path: $SNAPCRAFT_STAGE/opt/ros/kinetic
      
      # On Ubuntu machine
      # build-path: /opt/ros/kinetic

      # Run-time location of the underlay
      run-path: $SNAP/ros-base/opt/ros/kinetic
    # list of catking packages in the snap
    catkin-packages:
      - talker      
    after: [ros-base]

  # We can't just use roslaunch now, since that's contained in the
  # underlay. This part will tweak the environment a little to
  # utilize the underlay.
  run-system:
    plugin: dump
    stage: [bin/run-system]
    prime: [bin/run-system]

  # We need to create the $SNAP/ros-base mountpoint for the content
  # being shared.
  mountpoint:
    plugin: nil
    install: mkdir $SNAPCRAFT_PART_INSTALL/ros-base

But I am checking the snapcraft schema. I couldn't find "run-system:".

At the moment I can not able to use underlay.

I am able to build snaps without run-system.
But I can not able to use ROS commands like "rosrun", "roslaunch".

How can I resolve this issue?

**Comment by kyrofa** [comment]
Sorry for the delay, let's please continue this discussion in the forum.
