### ISSUE TITLE
When asking to release to a branch that's too long, a traceback is printed that gives no hints as to the source of the error

### ISSUE THREAD

**Issue by sergiusens** [snapcore/snapcraft#2028]
- [When asking to release to a branch that's too long, a traceback is printed that gives no hints as to the source of the error](https://bugs.launchpad.net/snapcraft/+bug/1750177)

**Comment by kyrofa** [comment]
Unfortunately, the store response is a 500 in this case, containing HTML and no clue as to what happened. We can stop tracing back, but the best we can do is say "Uh oh. Sorry." Check #2059 for details.
