### ISSUE TITLE
snap install process creates empty dirs on Home folder

### ISSUE THREAD

**Issue by mmartinortiz** [snapcore/snapcraft#2044]
After installing snaps like Firefox or Telegram, empty folders are created in the user's home according to `/etc/xdg/user-dirs.default`. The expected behaviour is the creation of folders (if needed) according to `$HOME/.config/user-dirs.dirs`.

This issue is also described [here](https://askubuntu.com/questions/989751/ubuntu-is-creating-empty-folders-in-home-directory) and reported also in the [Telegram snap repository](https://github.com/3v1n0/telegram-snap/issues/4).

Tested sytems:

- Ubuntu 17.10
  - snap    2.31.2
  - snapd   2.31.2
  - series  16
  - ubuntu  17.10
  - kernel  4.13.0-37-generic
- Elementary OS

**Comment by kyrofa** [comment]
It's also discussed in-depth [here](https://bugs.launchpad.net/snapd/+bug/1575053). Please use that for discussion, I'll close this one.
