### ISSUE TITLE
How to install packages from custom repositories on build.snapcraft?

### ISSUE THREAD

**Issue by martinrotter** [snapcore/snapcraft#2118]
My project needs GCC 7 (C++ 17 features) and Qt 5.7.0 or better.

These are obviously not available on builders which run build.snapcraft and thus my build fails - https://build.snapcraft.io/user/martinrotter/textosaurus

My yaml - https://github.com/martinrotter/textosaurus/blob/master/snapcraft.yaml

So my question: How to tell builder to install gcc-7 + newer Qt packages? Basically, I would like to run:
```
  sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  sudo add-apt-repository ppa:beineri/opt-qt594-trusty -y
  sudo apt-get update
  sudo apt-get -y install gcc-7 g++-7 qt59tools qt59base qt59svg
  
  sudo update-alternatives --remove-all gcc 
  sudo update-alternatives --remove-all g++
  sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 50
  sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 50
```
in builder environment, so that those packages are available for snap build. How to do that? I am total rookie in snap stuff.

**Comment by sergiusens** [comment]
Hi! You can use https://snapcraft.io/docs/package-repositories to do this.
