### ISSUE TITLE
gradle plugin doesn't generate a war

### ISSUE THREAD

**Issue by bsutton** [snapcore/snapcraft#2134]
I have a build.gradle that uses the 'war' gradle plugin to generate a war file.
If I run ./gradlew build I get the expected war file.

The gradle plug however essentially runs:

gradlew jar

The result is that the 'jar' task is executed and a jar is generated rather than the desired war file.
I'm no gradle expert but would it not make more sense to just run 'gradle build' ?

Alternatively add a gradle option to allow the desired task/tasks to be executed.
This would work for backward compatibility in that you could do:

gradle:
    task: [test, war]

If the task was not provided then it would default to 

gradle:
  tasks: [jar]

Currently the 'jar' task is just automatically appended to the 'gradle-option' list so this should work nicely.

**Comment by kyrofa** [comment]
For future reference, please note that we use launchpad for bugs, not github: https://bugs.launchpad.net/snapcraft
