### ISSUE TITLE
kde-neon extension support for Qt6

### ISSUE THREAD

**Issue by tsteven4** [snapcore/snapcraft#4148]
### What needs to get done

Support Qt6 applications as snaps.

### Why it needs to get done

Qt5 is nearing end of life.  Some applications require Qt6.

**Comment by lengau** [comment]
Pinging @ScarlettGatelyMoore on this since she'll know better than I do, but this is probably blocked on a qt6 release of KDE frameworks.

**Comment by ScarlettGatelyMoore** [comment]
That is correct. I have not yet created the qt6/kf6 content pack. It is planned for the very near future.

**Comment by leap-pea** [comment]
Hey,

what's the current state of snap and qt6? I'm currently building a snap for [riseup-vpn](https://snapcraft.io/riseup-vpn)/bitmask-vpn. We've updated to qt6 and I can't get it to work. Please read my comments about the situation: https://0xacab.org/leap/bitmask-vpn/-/issues/848#note_1205365

Can you please answer some questions?
- As our client application starts openvpn - Can we add/configure tun interfaces with strict confinement? It seems like all the existing extensions only work with strict confinement. And there is not suitable (snap) interface.
- Is qt6 supported? And if what's the current way to use it? Using "desktop helpers"? Or "extensions"?
- Why are the two PRs mentioned in the other issue not merged/commented?

Thanks in advance!

**Comment by lengau** [comment]
@ScarlettGatelyMoore has created an implemented a [`kde-neon-6` extension](https://github.com/canonical/snapcraft/blob/main/snapcraft/extensions/kde_neon_6.py) that works for KDE 6 apps. I can't find the `snapcraft.yaml` file for it, but the app appears to be pure-qt, so the full KDE 6 extension might be a bit excessive. The KDE team (again thanks to Scarlett) has published a [Qt6 SDK snap](https://snapcraft.io/kde-qt6-core22-sdk) and a [Qt6 content snap](https://snapcraft.io/kde-qt6-core22) that the KDE extension uses. While there's not a standalone qt6 extension, if you don't want to use the full KDE frameworks stuff, you could probably use the source of the KDE 6 extension and those qt6 snaps to update your snapcraft.yaml file.

Using the SDK snap and the content snap manually would allow you to use classic confinement (though yours might end up being the first classic confined snap to use that particular content snap).

I'm not an expert in snap permissions, and it depends how precisely your app works with the interfaces, but a strictly confined snap may be able to use the `network-control`, `network-manager` and/or `network-setup-control` [snapd interfaces](https://snapcraft.io/docs/network-interfaces) to do what you need. I'd recommend asking on the [snap forums](https://forum.snapcraft.io/), as the snapd developers (who know far more about the intricacies of the specific interfaces) are active there. The only other PR I can see referenced is #4294, which appears to have fallen off our radar - I've put it back up for us to check

**Comment by lengau** [comment]
Closing this since the kde-neon-6 extension exists
