### ISSUE TITLE
Entering the provider uses the hostname of the snapshot

### ISSUE THREAD

**Issue by sergiusens** [snapcore/snapcraft#4181]
### Bug Description

The base snapshot is keeping the hostname (snapcraft-<snap-name>) of the first project that is used to create that base.

### To Reproduce

- Use a clean environment (no existing LXD project)
- Use latest snapcraft
- create a new snap project (my-snap)
- create the snap
- create another snap project (my-other-snap)
- run `snapcraft pull --shell`
- notice the hostname of this environment is set to `snapcraft-my-snap` and not `snapcraft-my-other-snap`

### Environment

Ubuntu 22.04, snapcraft with LXD

### snapcraft.yaml

```shell
snapcraft init
```

### Relevant log output

```shell
sergiusens@imladris:~/repo/snaps/ansel$ snapcraft pull --shell
Launching instance...                                                          
Launching shell on build environment...                                        
snapcraft-pypi-server-charm-obs-on-amd64-for-amd64-2098342 ../project#
```

**Comment by mr-cal** [comment]
Resolved in `craft-providers` 1.10.1, which was updated in #4244
