### ISSUE TITLE
"snapcraft try" using provider LXD generates a prime/ directory with no payload

### ISSUE THREAD

**Issue by rpjday** [snapcore/snapcraft#4219]
### Bug Description

Building a trivial snap on Ubuntu 22.04 with snapcraft 7.4.3 and provider LXD with "snapcraft try", the eventual prime/ directory contains nothing but:

$ tree prime
prime
└── meta
    ├── gui
    └── snap.yaml
$

This appears to be entirely reproducible for me.

### To Reproduce

Pick a random snap and run "snapcraft try" using LXD provider -- the output suggests you can now run "snap try prime", but given that there is no meaningful payload, you get:

error: cannot try /home/rpjday/sc101v23/snapcraft-101-labs/basic-snap/prime: snap is
       unusable due to missing files; contact developer

### Environment

Ubuntu 22.04, snapcraft 7.4.3.

### snapcraft.yaml

```shell
name: basic-snap
base: core22 # the base snap is the execution environment for this snap
version: '0.99'
summary: Demo snap to show basic snap features.
description: |
  Snap to demo numerous basic snap properties and operations.

grade: devel
confinement: devmode

apps:
  basic-snap:
    command: basic.sh
  hello:
    command: hello.sh
  hi:
    command: d1/d2/hi.sh

parts:
  basic:
    source: src1/
    plugin: dump
  hello:
    source: src2/
    plugin: dump
  hi:
    source: src3/
    plugin: dump
```

### Relevant log output

```shell
$ snap try prime
error: cannot try /home/rpjday/sc101v23/snapcraft-101-labs/basic-snap/prime: snap is
       unusable due to missing files; contact developer
```

**Comment by mr-cal** [comment]
I can reproduce this issue.  
For core22, I believe the problem is that snapcraft is shutting down the instance instead of leaving it running.

**Comment by sergiusens** [comment]
@mr-cal, the prime directory actually gets created on the host and is mounted into the container. So if the first thing you ever do is run `snapcraft try`, then everything works. The problem is if you primed once before and then run try, and empty directory will take over the existing prime and since the lifecycle is not aware of this, there is no repriming taking place

**Comment by rpjday** [comment]
So all I need to do is advise to run "snapcraft try" first thing, and everything should be fine? I'm good with that.

**Comment by sergiusens** [comment]
Proposed #4347 as a hotfix to 7.5
