### ISSUE TITLE
lxd-type-base spread test is flaky due to lxd timeouts

### ISSUE THREAD

**Issue by lengau** [snapcore/snapcraft#4236]
### Bug Description

This spread test often breaks due to LXD timeouts when stopping the container. 

This may be relevant: https://discuss.linuxcontainers.org/t/failed-to-begin-transaction-context-deadline-exceeded/13247/6

### To Reproduce

Run the Ubuntu 20.04 spread tests in CI

### Relevant log output

https://github.com/snapcore/snapcraft/actions/runs/5391823831/jobs/9792027057#step:4:11778

```
+ /snap/bin/lxc start snapcraft-core20
+ /snap/bin/lxc exec snapcraft-core20 cat /etc/os-release
+ MATCH VERSION_CODENAME=focal
+ /snap/bin/lxc stop snapcraft-core20
Error: Failed shutting down instance, status is "Running": context deadline exceeded
Try `lxc info --show-log snapcraft-core20` for more info
-----
.
```

**Comment by sergiusens** [comment]
closed by https://github.com/snapcore/snapcraft/pull/4239
