### ISSUE TITLE
Abstract socket in listen-stream cause validation failure

### ISSUE THREAD

**Issue by phckopper** [snapcore/snapcraft#4287]
### Bug Description

When trying to declare an abstract socket in a `snapcraft.yaml` file it caused validation to fail, even though it's supported by `snapd` [[1]](https://snapcraft.io/docs/snapcraft-app-and-service-metadata) [[2]](https://forum.snapcraft.io/t/socket-activation-support/2050/7). I was able to trace this back to an incomplete regex used for validation that doesn't support the possibility of sockets in abstract namespaces [here](https://github.com/snapcore/snapcraft/blob/dbe76f21d0e670811a05f6fa7838e704bbfaa52d/snapcraft/projects.py#L175-L195).

### To Reproduce

Try to build the `snapcraft.yaml` file with `snapcraft -v`.

### Environment

Ubuntu 23.04, snapcraft 7.4.3

### snapcraft.yaml

```shell
name: lldpad
base: core22
confinement: devmode
description: 'Redacted'
summary: Link Layer Discovery Protocol Implementation (Runtime)
version: 1.1+git20221028.aa18720-1-snap
parts:
  lldpad:
    plugin: nil
    stage-packages:
    - lldpad
apps:
  lldpad:
    command: /usr/sbin/lldpad
    daemon: simple
    plugs:
      - network-bind
      - browser-support
    sockets:
      unix:
        listen-stream: "@snap.lldpad./com/intel/lldpad"
```

### Relevant log output

```shell
Starting Snapcraft 7.4.3
Logging execution to '/home/phckopper/.local/state/snapcraft/log/snapcraft-20230719-203033.689783.log'
Running on amd64 for amd64
Bad snapcraft.yaml content:
- '@snap.lldpad./com/intel/lldpad' is not a valid socket path (e.g. /tmp/mysocket.sock). (in field 'apps.lldpad.sockets.unix.listen-stream')
Full execution log: '/home/phckopper/.local/state/snapcraft/log/snapcraft-20230719-203033.689783.log
```

### Additional context

[How snapd validates internally](https://github.com/snapcore/snapd/blob/876953a4a80ee319aa4e175eaf81b0eefec6748c/snap/validate.go#L202)

**Comment by sergiusens** [comment]
Proposed hotfix https://github.com/snapcore/snapcraft/pull/4354
