### ISSUE TITLE
SNAPCRAFT_BUILD_ENVIRONMENT apparently takes precedence over "--use-lxd"

### ISSUE THREAD

**Issue by rpjday** [snapcore/snapcraft#4307]
### Bug Description

Despite what is printed here, https://snapcraft.io/docs/build-providers, if I set the env var SNAPCRAFT_BUILD_ENVIRONMENT=host, that appears to take priority over using "--use-lxd" on the command line.

### To Reproduce

Set env var SNAPCRAFT_BUILD_ENVIRONMENT=host, then try overriding that with "--use-lxd".

### Environment

Ubuntu 22.04

### snapcraft.yaml

```shell
Not relevant.
```

### Relevant log output

```shell
Build is done on host in destructive mode.
```

**Comment by mr-cal** [comment]
Need to merge https://github.com/snapcore/snapcraft/pull/4330 first
