### ISSUE TITLE
Update architectures documentation

### ISSUE THREAD

**Issue by mr-cal** [snapcore/snapcraft#4336]
### What needs to get done

The [architectures documentation](https://snapcraft.io/docs/architectures) needs to be improved, including:

- default behaviors (e.g. core22 builds for all architectures)
- description of architectural envvars
- description of cli options (`--target-arch`, `--build-for`)
- what happens in destructive mode (e.g. does the environment get cleaned?)
- validation rules and limitations

I would like to get ideas and feedback from @rpjday.

### Why it needs to get done

Architectures are complex and need thorough documentation.

**Comment by rpjday** [comment]
Working on it ...

**Comment by rpjday** [comment]
First thing I would do is confirm the full set of valid architectures; also, is there any command that lists them? The way "snapcraft plugins" lists plugins, etc? Is there any command that produces that list?

**Comment by cmatsuoka** [comment]
Consider adding a note to example 5 clarifying that Snapcraft won't cross-compile automatically, or maybe avoid using the term "cross-compilation" altogether.
