### ISSUE TITLE
Incorrect env set by desktop-launch for AD users

### ISSUE THREAD

**Issue by dargad** [snapcore/snapcraft#4348]
### Bug Description

When the logged in user comes from AD the [getent call](https://github.com/snapcore/snapcraft/blob/main/extensions/desktop/common/init#L42) returns an empty string making the REALHOME var having an incorrect value.

This makes some apps (e.g. snapped browsers like Firefox and Chromium) to incorrectly set their home under ~/snap/<browser>/... instead of /home/<user>. This nests directories like Downloads unnecessarily deep.

More details in [LP: #2025447](https://bugs.launchpad.net/bugs/2025447).

I've experimented with setting REALHOME to ${SNAP_REAL_HOME} with good results, but maybe the getent call has some other intended implications that I am not aware of.

### To Reproduce

1. Log in to Gnome as an Active Directory user.
2. Launch browser (firefox or chrome) - make sure there's no existing config (we are interested in the default Downloads location).
3. Download a file via the browser.
4. Check where it was downloaded.

### Environment

Up to date Ubuntu 22.04.3 connected to AD according to [this tutorial](https://ubuntu.com/server/docs/service-sssd-ad).

### snapcraft.yaml

```shell
Reproducible with firefox and chromium available from the snap store.

- firefox (116.0.3 Mozilla Firefox Snap for Ubuntu canonical-002 - 1.0)
- chromium (Version 116.0.5845.110 (Official Build) snap (64-bit))
- snapd 2.58+22.04.1
```

### Relevant log output

```shell
Default download dir is:
~/snap/firefox/common/Downloads
~/snap/chromium/current/Downloads
```

**Comment by kenvandine** [comment]
@sergio-costas can you please take a look at this?  Our use of REALHOME predated the existence of SNAP_REAL_HOME.  I suspect we can just replace REALHOME with SNAP_REAL_HOME, but that requires some testing to ensure it doesn't regress.

**Comment by sergio-costas** [comment]
@kenvandine I'm on it.

**Comment by sergio-costas** [comment]
@dargad We prepared a patched snap. Can you test it? To install it, just run in a terminal

    sudo snap refresh gnome-42-2204 --channel=latest/stable/ad-fix

and to revert to the stable one, just run

    sudo snap refresh gnome-42-2204 --channel=latest/stable

**Comment by dargad** [comment]
Thank you @sergio-costas. I have just tested it and can confirm that REALHOME is set correctly with gnome from the latest/stable/ad-fix channel.
This results in both: Firefox and Chromium downloading files to ~/Downloads by default.

**Comment by sergio-costas** [comment]
Good news, then. Thanks!
