### ISSUE TITLE
Regression in handling `remote-build`

### ISSUE THREAD

**Issue by dilyn-corner** [snapcore/snapcraft#4357]
### Bug Description

When using `snapcraft remote-build` to have Snapcraft dispatch a build to Launchpad for building the snapd snap, an erroneous message is received indicating that the version of snapcraft being used to initiate the build does not support snapd's base. While this is true, this fact should have no bearing on whether or not such a build can be sent to Launchpad -- the host's version of snapcraft is unrelated to the Launchpad build environment.

### To Reproduce

```
snap refresh --channel=latest/edge snapcraft
git clone https://github.com/snapcore/snapd
cd snapd
snapcraft remote-build --launchpad-accept-public-upload
```

### Environment

A variant of Ubuntu 23.04, testing with snapcraft latest/edge. Trying to build snapd from `HEAD`, setting `SNAPCRAFT_VERBOSITY_LEVEL=verbose; SNAPCRAFT_BUILD_INFO=1`.

Builds indicated above previously succeeded on earlier revisions of `snapcraft`, at least in June. Perhaps earlier.

### snapcraft.yaml

```shell
Not especially relevant in this instance, but for the curious:
https://github.com/snapcore/snapd/blob/master/build-aux/snap/snapcraft.yaml
```

### Relevant log output

```shell
When you run the reproduction steps above, you should meet the following message:


dilyn@Ares:~/work/canonical/snapd -> snapcraft remote-build --launchpad-accept-public-upload
Starting Snapcraft 7.5.2.post81+git97911564                                                                              
Logging execution to '/home/dilyn/.local/state/snapcraft/log/snapcraft-20230907-122433.257422.log'                       
snapcraft remote-build is experimental and is subject to change - use with caution.                                      
'core' is not supported on this version of Snapcraft.                                                                    
Recommended resolution: Install from or refresh to the '4.x' channel.                                                    
For more information, check out: https://snapcraft.io/docs/base-snaps                                                    
Full execution log: '/home/dilyn/.local/state/snapcraft/log/snapcraft-20230907-122433.257422.log' 
```
```


### Additional context

This behavior is not present on 7.x/* or latest/stable, which means it is some sort of regression 
between the 7.5.2 tag and 7.5.2.post81+git97911564.

**Comment by sergiusens** [comment]
After some research and deliberation, this seems appropriate, core is only supported on 4.x; Snapcraft 8 removes support for core and core18
