### ISSUE TITLE
Improve UX for new remote-build

### ISSUE THREAD

**Issue by mr-cal** [snapcore/snapcraft#4399]
### What needs to get done

Run `snapcraft remote-build` in each verbosity level and ensure it gives the right logging output.

In summary:
- Shorten, reword, and clarify messages
- Use the right emitter calls in `snapcraft/commands/remote.py` 
    - (i.e. `emit.message()`, `emit.progress()`, `emit.progress(permanent=True)`, etc)
- Use the right log levels in `snapcraft/remote/`

### Why it needs to get done

The UX for the new remote-build is average because I wasn't focusing on this during the migration.  It can be improved quite a bit.

**Comment by lengau** [comment]
This probably needs multiline support in `craft-parts`, right?

**Comment by mr-cal** [comment]
I think so.  As a temporary workaround, it's currently getting logged on one line:

`Building:: Build status as of 2023-10-06 14:34:15.554752:  arch='arm64' state='Needs building'`

Certainly not ideal.
