### ISSUE TITLE
Login error user story needs to be cleaned up

### ISSUE THREAD

**Issue by sergiusens** [snapcore/snapcraft#4414]
### Bug Description

- We want to focus on the new, the old needs to be an appendix (https://snapcraft.io/docs/snapcraft-authentication)
- the gnome-keyring option does not work anymore
- the error message when it does not work is not helpful

### To Reproduce

multipass shell
snap install snapcraft --classic
snapcraft login

### Environment

Multipass Ubuntu 22.04

### snapcraft.yaml

```shell
n/a
```

### Relevant log output

```shell
n/a
```

**Comment by sergiusens** [comment]
Depends on canonical/craft-store#109

**Comment by mr-cal** [comment]
I have questions about all 3 bullet points in the bug:

> - We want to focus on the new, the old needs to be an appendix (https://snapcraft.io/docs/snapcraft-authentication)

1. Does "old" mean:
  - all the references of `snapcraft login --with` for snapcraft 6.x?
  - how to export snapcraft 6.x credentials to snapcraft 7.x?

> - the gnome-keyring option does not work anymore

Should I remove this from the documentation?

> - the error message when it does not work is not helpful

Following the reproducer:
```shell
multipass shell
snap install snapcraft --classic
snapcraft login
```

I get the error:
```shell
snapcraft login
craft-store error: No keyring found to store or retrieve credentials from.
Recommended resolution: Ensure the keyring is working or SNAPCRAFT_STORE_CREDENTIALS is correctly exported into the environment
For more information, check out: https://snapcraft.io/docs/snapcraft-authentication
Full execution log: '/home/ubuntu/.local/state/snapcraft/log/snapcraft-20231031-123017.319180.log'
```

What should it be displaying instead?

**Comment by mr-cal** [comment]
Notes from an offline team conversation:

- `snapcraft login` is designed to work on a desktop (non-headless) system where a keyring is already properly installed.
- `snapcraft login` does not work on headless systems.  The section about the gnome keyring should be removed from the documentation.  Instead, `snapcraft export-login` should be used/credentials from a desktop should be exported.
- The current error message is fine, it just links to a documentation page that needs to be rewritten.
