### ISSUE TITLE
regression: remote-build doesn't accept comma-seperated architectures

### ISSUE THREAD

**Issue by mr-cal** [snapcore/snapcraft#4516]
### Bug Description

In snapcraft 8.0.1, `snapcraft remote-build --architectures=amd64,arm64` fails to split a list of architectures.

[This logic](https://github.com/snapcore/snapcraft/blob/ffbdabf53de21606d9d12e15f16d4bca5e4423a5/snapcraft_legacy/cli/remote.py#L267) needs to be added to the remote-build cli handler.

### To Reproduce

`snapcraft remote-build --architectures=amd64,arm64`

### Environment

n/a

### snapcraft.yaml

```shell
n/a
```

### Relevant log output

```shell
2024-01-10 10:21:08.174 remote-build error: Architecture not supported by the remote builder.
The following architectures are not supported by the remote builder: ['amd64,arm64'].
Please remove them from the architecture list and try again.
```

**Comment by mr-cal** [comment]
Regression fixed in #4543

**Comment by JGCarroll** [comment]
Hi,

As of Snapcraft 8.2.7, this appears to have returned in the exact same manner as it were originally.

**Comment by mr-cal** [comment]
Thanks, unfortunately Snapcraft has regressed on this again.  I will track this in a new issue.
